# Generated by Django 2.0.5 on 2018-05-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnimationName', models.CharField(max_length=255)),
                ('AnimationStateName', models.CharField(max_length=255)),
                ('AnimationParamName', models.CharField(blank=True, max_length=255, null=True)),
                ('AnimationParamVariable', models.FloatField(blank=True, default=0, null=True)),
                ('AnimationParam2Name', models.CharField(blank=True, max_length=255, null=True)),
                ('AnimationParam2Variable', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Describe', models.CharField(blank=True, max_length=255, null=True)),
                ('AudioType', models.IntegerField(default=0)),
                ('AudioName', models.CharField(max_length=255)),
                ('AudioVolumn', models.FloatField(default=0)),
                ('AudioLoopParamName', models.BooleanField(default=False)),
                ('Audio3DMinDistance', models.FloatField(blank=True, default=0, null=True)),
                ('Audio3DMaxDistance', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardBagStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardBagType', models.IntegerField(default=0)),
                ('CardBagProbability', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CardStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardProbability', models.IntegerField(default=0)),
                ('CardRes', models.CharField(max_length=255)),
                ('CardStar', models.IntegerField(default=0)),
                ('RecycleCoin', models.IntegerField(default=0)),
                ('CardBagID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CardBagID_Reverse', to='app.CardBagStatic')),
            ],
        ),
        migrations.CreateModel(
            name='CatLevelStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelNum', models.IntegerField(default=0)),
                ('ExpNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CatPathStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TriggerGrassID', models.TextField(blank=True, null=True)),
                ('TriggerHealthPointMin', models.IntegerField(default=0)),
                ('TriggerHealthPointMax', models.IntegerField(default=0)),
                ('TriggerCatLevelMin', models.IntegerField(default=0)),
                ('TriggerCatLevelMax', models.IntegerField(default=0)),
                ('TriggerBaseCardBagID', models.TextField()),
                ('TriggerRareCardBagID', models.TextField()),
                ('TriggerToyCardConditionID1', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerCardProbability1', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerToyCardBagID1', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerToyCardConditionID2', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerCardProbability2', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerToyCardBagID2', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerToyCardConditionID3', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerCardProbability3', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerToyCardBagID3', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerToyCardConditionID4', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerCardProbability4', models.IntegerField(blank=True, default=0, null=True)),
                ('TriggerToyCardBagID4', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatType', models.IntegerField(default=0)),
                ('CatBaseResource', models.CharField(max_length=255)),
                ('CatWholeBodyMeshName', models.CharField(max_length=255)),
                ('CatBodyNotEarMeshName', models.CharField(max_length=255)),
                ('CatPartResource', models.TextField()),
                ('IdleBehaviorParam', models.CharField(blank=True, max_length=255, null=True)),
                ('FeedBehaviorParam', models.CharField(blank=True, max_length=255, null=True)),
                ('LazerBehaviorParam', models.CharField(blank=True, max_length=255, null=True)),
                ('DryerBehaviorParam', models.CharField(blank=True, max_length=255, null=True)),
                ('HealthPoint', models.IntegerField(default=0)),
                ('HealthMaxPoint', models.IntegerField(default=0)),
                ('WeightPoint', models.IntegerField(default=0)),
                ('WeightMaxPoint', models.IntegerField(default=0)),
                ('ExpPoint', models.IntegerField(default=0)),
                ('ExpAddTimeSpan', models.IntegerField(default=0)),
                ('ExpAddNum', models.IntegerField(default=0)),
                ('HappyPointAddHealthPoint', models.IntegerField(default=0)),
                ('HungryPointAddHealthPoint', models.IntegerField(default=0)),
                ('HappyInitialPoint', models.IntegerField(default=0)),
                ('HappyMaxPoint', models.IntegerField(default=0)),
                ('HungryInitialPoint', models.IntegerField(default=0)),
                ('HungryMaxPoint', models.IntegerField(default=0)),
                ('LevelPoint', models.IntegerField(default=0)),
                ('MaxLevelPoint', models.IntegerField(blank=True, default=0, null=True)),
                ('NexLevelID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NexLevelID_Reverse', to='app.CatStatic')),
            ],
        ),
        migrations.CreateModel(
            name='ConstStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatTriggerTime', models.IntegerField(default=0)),
                ('MaxRestoreCardNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CostumeStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostumeType', models.IntegerField(default=0)),
                ('BodyWithEar', models.BooleanField(default=False)),
                ('CostumeResource', models.CharField(max_length=255)),
                ('CostumeHangPoint', models.CharField(max_length=255)),
                ('CostumeCharm', models.IntegerField(default=0)),
                ('CostumePrice', models.IntegerField(default=0)),
                ('MintPrice', models.IntegerField(default=0)),
                ('CostumeIconName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTaskRewardStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayNum', models.IntegerField(blank=True, default=0, null=True)),
                ('CreditExp', models.IntegerField(blank=True, default=0, null=True)),
                ('CreditCoin', models.IntegerField(blank=True, default=0, null=True)),
                ('CreditMint', models.IntegerField(blank=True, default=0, null=True)),
                ('CreditPropID', models.IntegerField(blank=True, default=0, null=True)),
                ('CreditCostum', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTaskStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DailyTaskProbability', models.IntegerField(default=0)),
                ('EventType', models.IntegerField(default=0)),
                ('TaskEventNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DialogStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DialogType', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExpAddStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelPoint', models.IntegerField(default=0)),
                ('ExpPoint', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodType', models.IntegerField(default=0)),
                ('UnlockCatAge', models.IntegerField(blank=True, default=0, null=True)),
                ('UnlockCoin', models.IntegerField(blank=True, default=0, null=True)),
                ('UnlockEnjoy', models.BooleanField(default=False)),
                ('Coin', models.IntegerField(default=0)),
                ('Mint', models.IntegerField(default=0)),
                ('HungryPoint', models.IntegerField(default=0)),
                ('HappyPoint', models.IntegerField(default=0)),
                ('LevelPoint', models.IntegerField(default=0)),
                ('HealthPoint', models.IntegerField(default=0)),
                ('FoodIconName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameType', models.IntegerField(default=0)),
                ('GameIcon', models.CharField(max_length=255)),
                ('GameResource', models.CharField(blank=True, max_length=255, null=True)),
                ('GameDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('MinHungryNum', models.IntegerField(default=0)),
                ('HappyPerTime', models.IntegerField(default=0)),
                ('AddHappyNum', models.IntegerField(default=0)),
                ('MaxHappyNum', models.IntegerField(default=0)),
                ('ExpPerTime', models.IntegerField(default=0)),
                ('AddExpNum', models.IntegerField(default=0)),
                ('MaxExpNum', models.IntegerField(default=0)),
                ('LogicGameParam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoldMintShopStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopItemType', models.IntegerField(default=0)),
                ('ShopItemTagType', models.IntegerField(blank=True, default=0, null=True)),
                ('ShopItemPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('ShopItemNum', models.IntegerField(blank=True, default=0, null=True)),
                ('ShopItemSequence', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LanguageEngInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('LanguageChnInfo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropShopStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopItemType', models.IntegerField(default=0)),
                ('ShopItemID', models.IntegerField(default=0)),
                ('ShopItemPrice', models.IntegerField(default=0)),
                ('ShopItemNum', models.IntegerField(default=0)),
                ('ShopItemSequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PropStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropType', models.IntegerField(default=0)),
                ('PropIcon', models.CharField(max_length=255)),
                ('PropMaxNum', models.IntegerField(default=0)),
                ('Coin', models.IntegerField(default=0)),
                ('Mint', models.IntegerField(default=0)),
                ('PropDescirption', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PropDescirption_Reverse', to='app.LanguageStatic')),
                ('PropName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PropName_Reverse', to='app.LanguageStatic')),
            ],
        ),
        migrations.CreateModel(
            name='SevenDaySignStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayNum', models.IntegerField(default=0)),
                ('AddCoin', models.IntegerField(blank=True, default=0, null=True)),
                ('AddPropID', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGuideConditionStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserGuideConditionType', models.IntegerField(default=0)),
                ('ConditionParam', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGuideEventStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserGuideEventType', models.IntegerField(default=0)),
                ('EventParam', models.TextField()),
                ('NextGuideEventIDArray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NextGuideEventIDArray_Reverses', to='app.UserGuideEventStatic')),
            ],
        ),
        migrations.CreateModel(
            name='UserGuideStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NextGuideID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NextGuideID_Reverses', to='app.UserGuideStatic')),
                ('UserGuideCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserGuideCondition_Reverses', to='app.UserGuideConditionStatic')),
                ('UserGuideEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserGuideEvent_Reverses', to='app.UserGuideEventStatic')),
            ],
        ),
        migrations.CreateModel(
            name='WeightAddStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeightNumHealthZeroPoint', models.IntegerField(default=0)),
                ('WeightNumHealthOnePoint', models.IntegerField(default=0)),
                ('WeightNumHealthTwoPoint', models.IntegerField(default=0)),
                ('WeightNumHealthThreePoint', models.IntegerField(default=0)),
                ('WeightNumHealthFourPoint', models.IntegerField(default=0)),
                ('WeightNumHealthFivePoint', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='dialogstatic',
            name='DialogInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DialogInfo_Reverse', to='app.LanguageStatic'),
        ),
        migrations.AddField(
            model_name='dialogstatic',
            name='DialogTitle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DialogTitle_Reverse', to='app.LanguageStatic'),
        ),
        migrations.AddField(
            model_name='dailytaskstatic',
            name='DailyTaskName',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DailyTaskName_Reverse', to='app.LanguageStatic'),
        ),
        migrations.AddField(
            model_name='costumestatic',
            name='CostumeName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CostumeName_Reverse', to='app.LanguageStatic'),
        ),
        migrations.AddField(
            model_name='catpathstatic',
            name='PathDescirption',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PathDescirption_Reverse', to='app.LanguageStatic'),
        ),
        migrations.AddField(
            model_name='catpathstatic',
            name='PathName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PathName_Reverse', to='app.LanguageStatic'),
        ),
        migrations.AddField(
            model_name='cardstatic',
            name='CardDescirption',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CardDescirption_Reverse', to='app.LanguageStatic'),
        ),
        migrations.AddField(
            model_name='cardstatic',
            name='CardName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CardName_Reverse', to='app.LanguageStatic'),
        ),
        migrations.AddField(
            model_name='cardbagstatic',
            name='CardBagDescirption',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CardBagDescirption_Reverse', to='app.LanguageStatic'),
        ),
    ]
