# Generated by Django 2.0.5 on 2018-05-23 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstatic',
            name='CardBagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CardBagIDRelated', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerBaseCardBagID',
            field=models.ManyToManyField(related_name='TriggerBaseCardBagIDRelated', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerGrassID',
            field=models.ManyToManyField(blank=True, null=True, related_name='TriggerGrassIDRelated', to='app.PropStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerRareCardBagID',
            field=models.ManyToManyField(blank=True, null=True, related_name='TriggerRareCardBagIDRelated', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerToyCardBagID1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TriggerToyCardBagID1Related', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerToyCardBagID2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TriggerToyCardBagID2Related', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerToyCardBagID3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TriggerToyCardBagID3Related', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerToyCardBagID4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TriggerToyCardBagID4Related', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerToyCardBagID5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TriggerToyCardBagID5Related', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='catpathstatic',
            name='TriggerToyCardBagID6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TriggerToyCardBagID6Related', to='app.CardBagStatic'),
        ),
        migrations.AlterField(
            model_name='costumestatic',
            name='CostumeMatchedCat',
            field=models.ManyToManyField(related_name='CostumeMatchedCatRelated', to='app.CatStatic'),
        ),
        migrations.AlterField(
            model_name='costumestatic',
            name='CostumeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CostumeNameRelated', to='app.LanguageStatic'),
        ),
        migrations.AlterField(
            model_name='dailytaskstatic',
            name='DailyTaskName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DailyTaskNameRelated', to='app.LanguageStatic'),
        ),
        migrations.AlterField(
            model_name='dialogstatic',
            name='DialogInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DialogInfoRelated', to='app.LanguageStatic'),
        ),
        migrations.AlterField(
            model_name='dialogstatic',
            name='DialogTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DialogTitleRelated', to='app.LanguageStatic'),
        ),
        migrations.AlterField(
            model_name='propstatic',
            name='PropDescirption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropDescirptionRelated', to='app.LanguageStatic'),
        ),
        migrations.AlterField(
            model_name='propstatic',
            name='PropName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropNameRelated', to='app.LanguageStatic'),
        ),
        migrations.AlterField(
            model_name='userguidestatic',
            name='UserGuideCondition',
            field=models.ManyToManyField(related_name='UserGuideConditionRelated', to='app.UserGuideConditionStatic'),
        ),
        migrations.AlterField(
            model_name='userguidestatic',
            name='UserGuideEvent',
            field=models.ManyToManyField(related_name='UserGuideEventRelated', to='app.UserGuideEventStatic'),
        ),
    ]
